pipeline {
    agent any
    stages {
        stage ('First stage') {
            steps {
                echo 'First stage done!'
            }
        }
        stage('Build') {
            steps {
                echo 'fake building'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
